# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'SwiftComponent' do
  use_frameworks!

  # Pods for SwiftComponent
  pod 'SnapKit'
  pod 'MBProgressHUD'
#  pod 'NVActivityIndicatorView'

end
